#!usr/bin/env bash

# set waybar
ln -sf ~/.config/HyprV/waybar/conf/config.jsonc ~/.config/waybar/config.jsonc
ln -sf ~/.config/HyprV/waybar/style/style.css ~/.config/waybar/style.css

# set mako
ln -sf ~/.config/HyprV/mako/conf/config ~/.config/mako/config

# set wofi
ln -sf ~/.config/HyprV/wofi/style/style.css ~/.config/wofi/style.css
ln -sf ~/.config/HyprV/wofi/config ~/.config/wofi/config




